components:
  schemas:
    # Common models
    Timestamp:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
          description: Date and time when this record was created
        created_by:
          type: string
          description: User who created this record
        updated_at:
          type: string
          format: date-time
          description: Date and time when this record was last updated
        updated_by:
          type: string
          description: User who last updated this record
        deleted_at:
          type: string
          format: date-time
          description: Date and time when this record was marked as deleted
          nullable: true
    
    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: Current page number
        limit:
          type: integer
          description: Number of records per page
        total_pages:
          type: integer
          description: Total number of pages
        total_records:
          type: integer
          description: Total number of records
    
    # Party models
    PartyListItem:
      type: object
      properties:
        party_id:
          type: string
          description: Unique identifier for the party
        party_name:
          type: string
          description: The name of the party as it is known in business
        party_type:
          type: string
          enum: [Person, Organization]
          description: Type of party
        status:
          type: string
          enum: [Active, Inactive, Merged, Deleted]
          description: Current status of the party
        is_golden_record:
          type: boolean
          description: Flag indicating if this is the golden record
    
    PartyBase:
      type: object
      required:
        - party_name
        - party_type
      properties:
        party_name:
          type: string
          description: The name of the party as it is known in business
        party_type:
          type: string
          enum: [Person, Organization]
          description: Type of party
        status:
          type: string
          enum: [Active, Inactive, Merged, Deleted]
          default: Active
          description: Current status of the party
        data_source_system:
          type: string
          description: System where this party data originated
        data_source_id:
          type: string
          description: ID of this party in the source system
        party_identification:
          type: string
          description: A general identification for the party (e.g., TaxID)
    
    PersonBase:
      type: object
      required:
        - first_name
        - last_name
      properties:
        first_name:
          type: string
          description: First name of the person
        middle_name:
          type: string
          description: Middle name of the person
          nullable: true
        last_name:
          type: string
          description: Last name of the person
        given_name:
          type: string
          description: Given name of the person (if different from first name)
          nullable: true
        family_name:
          type: string
          description: Family name of the person (if different from last name)
          nullable: true
        birth_date:
          type: string
          format: date
          description: Date of birth
          nullable: true
        gender:
          type: string
          description: Gender of the person
          nullable: true
        marital_status:
          type: string
          description: Marital status of the person
          nullable: true
        nationality:
          type: string
          description: Nationality of the person
          nullable: true
        residence_country:
          type: string
          description: Country of residence
          nullable: true
        ethnicity:
          type: string
          description: Ethnicity of the person
          nullable: true
        religion:
          type: string
          description: Religion of the person
          nullable: true
        preferred_language:
          type: string
          description: Preferred language for communication
          nullable: true
        residential_status:
          type: string
          description: Residential status in the country of residence
          nullable: true
    
    OrganizationBase:
      type: object
      required:
        - organization_name
      properties:
        organization_name:
          type: string
          description: Legal name of the organization
        trading_name:
          type: string
          description: Name under which the organization conducts business
          nullable: true
        organization_type:
          type: string
          description: Type of organization (e.g., Corporation, LLC, Partnership)
          nullable: true
        organization_sector:
          type: string
          description: Business sector of the organization
          nullable: true
        registration_date:
          type: string
          format: date
          description: Date of registration/incorporation
          nullable: true
        registration_country:
          type: string
          description: Country of registration
          nullable: true
        tax_country:
          type: string
          description: Country for tax purposes
          nullable: true
        organization_structure:
          type: string
          description: Structure of the organization
          nullable: true
        employee_count:
          type: integer
          description: Number of employees
          nullable: true
        annual_revenue:
          type: number
          format: double
          description: Annual revenue of the organization
          nullable: true
        registration_authority:
          type: string
          description: Authority with which the organization is registered
          nullable: true
        website:
          type: string
          description: Official website of the organization
          nullable: true
        parent_organization_id:
          type: string
          description: ID of the parent organization if any
          nullable: true 