# Directory reference models
PartyDirectoryReference:
  type: object
  properties:
    reference_id:
      type: string
      description: Unique identifier for this reference
    party_id:
      type: string
      description: ID of the party this reference belongs to
    directory_name:
      type: string
      description: Name of the external directory
    directory_entry_id:
      type: string
      description: ID of the party in the external directory
    directory_entry_type:
      type: string
      description: Type of entry in the directory
      nullable: true
    directory_entry_date:
      type: string
      format: date
      description: Date of the entry in the directory
      nullable: true
    directory_valid_period:
      type: string
      description: Period for which the directory entry is valid
      nullable: true
    is_verified:
      type: boolean
      description: Flag indicating if this reference has been verified
      default: false
    verification_date:
      type: string
      format: date
      description: Date when this reference was verified
      nullable: true
    verification_method:
      type: string
      description: Method used to verify this reference
      nullable: true
    timestamps:
      $ref: '#/components/schemas/Timestamp'

# Relationship models
PartyRelationshipListItem:
  type: object
  properties:
    relationship_id:
      type: string
      description: Unique identifier for this relationship
    from_party_id:
      type: string
      description: ID of the source party
    from_party_name:
      type: string
      description: Name of the source party
    to_party_id:
      type: string
      description: ID of the target party
    to_party_name:
      type: string
      description: Name of the target party
    relationship_type:
      type: string
      description: Type of relationship between the parties
    status:
      type: string
      enum: [Active, Inactive, Suspended, Terminated]
      description: Current status of the relationship
    start_date:
      type: string
      format: date
      description: Date when this relationship started
    end_date:
      type: string
      format: date
      description: Date when this relationship ended
      nullable: true

PartyRelationshipBase:
  type: object
  required:
    - from_party_id
    - to_party_id
    - relationship_type
    - start_date
  properties:
    from_party_id:
      type: string
      description: ID of the source party
    to_party_id:
      type: string
      description: ID of the target party
    relationship_type:
      type: string
      description: Type of relationship between the parties
    relationship_validity_period:
      type: string
      description: The period for which this relationship is valid
      nullable: true
    start_date:
      type: string
      format: date
      description: Date when this relationship started
    end_date:
      type: string
      format: date
      description: Date when this relationship ended
      nullable: true
    status:
      type: string
      enum: [Active, Inactive, Suspended, Terminated]
      default: Active
      description: Current status of the relationship
    description:
      type: string
      description: Description of the relationship
      nullable: true
    priority:
      type: integer
      description: Priority of this relationship
      nullable: true
    is_bidirectional:
      type: boolean
      description: Flag indicating if this relationship is bidirectional
      default: false

PartyRelationshipCreate:
  allOf:
    - $ref: '#/components/schemas/PartyRelationshipBase'

PartyRelationshipUpdate:
  type: object
  properties:
    relationship_validity_period:
      type: string
      description: The period for which this relationship is valid
      nullable: true
    end_date:
      type: string
      format: date
      description: Date when this relationship ended
      nullable: true
    status:
      type: string
      enum: [Active, Inactive, Suspended, Terminated]
      description: Current status of the relationship
    description:
      type: string
      description: Description of the relationship
      nullable: true
    priority:
      type: integer
      description: Priority of this relationship
      nullable: true
    is_bidirectional:
      type: boolean
      description: Flag indicating if this relationship is bidirectional

CustomerRelationshipBase:
  type: object
  required:
    - customer_type
  properties:
    customer_type:
      type: string
      description: Type of customer (e.g., Individual, Business, Government)
    customer_category:
      type: string
      description: Category of customer (e.g., Premium, Standard, Basic)
      nullable: true
    customer_risk_rating:
      type: string
      description: Risk rating of the customer
      nullable: true
    account_manager_id:
      type: string
      description: ID of the account manager for this customer
      nullable: true
    lifecycle_stage:
      type: string
      description: Lifecycle stage of the customer (e.g., Prospect, Active, Dormant)
      nullable: true
    credit_limit:
      type: number
      format: double
      description: Credit limit for the customer
      nullable: true
    payment_terms:
      type: string
      description: Payment terms for the customer
      nullable: true
    onboarding_date:
      type: string
      format: date
      description: Date when the customer was onboarded
      nullable: true
    kyc_status:
      type: string
      enum: [Not Started, In Progress, Completed, Failed, Expired]
      description: Know Your Customer status
      nullable: true
    kyc_review_date:
      type: string
      format: date
      description: Date when KYC was last reviewed
      nullable: true 