  /mdm/match:
    post:
      summary: Match parties
      description: Find potential matching parties based on input criteria
      operationId: matchParties
      tags:
        - MDM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  
  /mdm/merge:
    post:
      summary: Merge parties
      description: Merge two or more parties into a single golden record
      operationId: mergeParties
      tags:
        - MDM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MergeRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MergeResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  
  /mdm/unmerge/{merge_id}:
    post:
      summary: Unmerge parties
      description: Unmerge previously merged parties
      operationId: unmergeParties
      tags:
        - MDM
      parameters:
        - name: merge_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the merge operation
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnmergeResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  
  /mdm/match-rules:
    get:
      summary: Get match rules
      description: Retrieve a list of party matching rules
      operationId: getMatchRules
      tags:
        - MDM
      parameters:
        - name: active
          in: query
          schema:
            type: boolean
          description: Filter by active status
        - name: party_type
          in: query
          schema:
            type: string
            enum: [Person, Organization, Both]
          description: Filter by party type
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of records per page
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MatchRuleListItem'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Create a match rule
      description: Create a new party matching rule
      operationId: createMatchRule
      tags:
        - MDM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchRuleCreate'
      responses:
        '201':
          description: Match rule created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchRuleResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError' 