# Location models
PartyLocationCreate:
  type: object
  required:
    - location_type
    - address_line_1
    - city
    - country
  properties:
    location_type:
      type: string
      description: Type of location (e.g., Registered, Business, Residential)
    address_line_1:
      type: string
      description: First line of the address
    address_line_2:
      type: string
      description: Second line of the address
      nullable: true
    address_line_3:
      type: string
      description: Third line of the address
      nullable: true
    city:
      type: string
      description: City of the address
    state_province:
      type: string
      description: State or province of the address
      nullable: true
    postal_code:
      type: string
      description: Postal or ZIP code of the address
      nullable: true
    country:
      type: string
      description: Country of the address
    is_primary:
      type: boolean
      description: Flag indicating if this is the primary location
      default: false
    latitude:
      type: number
      format: double
      description: Latitude coordinate of the address
      nullable: true
    longitude:
      type: number
      format: double
      description: Longitude coordinate of the address
      nullable: true
    effective_from:
      type: string
      format: date
      description: Date from which this address is effective
      nullable: true
    effective_to:
      type: string
      format: date
      description: Date until which this address is effective
      nullable: true

PartyLocation:
  allOf:
    - $ref: '#/components/schemas/PartyLocationCreate'
    - type: object
      properties:
        location_id:
          type: string
          description: Unique identifier for this location
        party_id:
          type: string
          description: ID of the party this location belongs to
        is_valid:
          type: boolean
          description: Flag indicating if this address has been validated
          default: false
        validation_date:
          type: string
          format: date
          description: Date when this address was validated
          nullable: true
        validation_method:
          type: string
          description: Method used to validate this address
          nullable: true
        timestamps:
          $ref: '#/components/schemas/Timestamp'

# Contact point models
ContactPointCreate:
  type: object
  required:
    - contact_type
    - contact_value
  properties:
    contact_type:
      type: string
      description: Type of contact (e.g., Email, Phone, PostalAddress, SocialNetwork)
    contact_value:
      type: string
      description: Value of the contact point (e.g., email address, phone number)
    is_primary:
      type: boolean
      description: Flag indicating if this is the primary contact point of its type
      default: false
    purpose:
      type: string
      description: Purpose of this contact point (e.g., Business, Personal, Billing)
      nullable: true
    effective_from:
      type: string
      format: date
      description: Date from which this contact point is effective
      nullable: true
    effective_to:
      type: string
      format: date
      description: Date until which this contact point is effective
      nullable: true

ContactPoint:
  allOf:
    - $ref: '#/components/schemas/ContactPointCreate'
    - type: object
      properties:
        contact_id:
          type: string
          description: Unique identifier for this contact point
        party_id:
          type: string
          description: ID of the party this contact point belongs to
        is_valid:
          type: boolean
          description: Flag indicating if this contact point has been validated
          default: false
        validation_date:
          type: string
          format: date
          description: Date when this contact point was validated
          nullable: true
        validation_method:
          type: string
          description: Method used to validate this contact point
          nullable: true
        timestamps:
          $ref: '#/components/schemas/Timestamp'

# Person profile models
PersonProfile:
  type: object
  properties:
    person_profile_id:
      type: string
      description: Unique identifier for this profile
    party_id:
      type: string
      description: ID of the person this profile belongs to
    political_exposure_type:
      type: string
      enum: [Foreign, Domestic, None]
      description: Type of political exposure
      nullable: true
    political_exposure_description:
      type: string
      description: Description of the political exposure
      nullable: true
    education_level:
      type: string
      description: Highest level of education
      nullable: true
    profession:
      type: string
      description: Current profession
      nullable: true
    income_range:
      type: string
      description: Income range
      nullable: true
    wealth_source:
      type: string
      description: Source of wealth
      nullable: true
    employment_status:
      type: string
      description: Current employment status
      nullable: true
    employer_name:
      type: string
      description: Name of the employer
      nullable: true
    job_title:
      type: string
      description: Job title
      nullable: true
    family_size:
      type: integer
      description: Number of family members
      nullable: true
    timestamps:
      $ref: '#/components/schemas/Timestamp' 