  /parties/{party_id}/identifications:
    get:
      summary: Get party identifications
      description: Retrieve all identifications for a specific party
      operationId: getPartyIdentifications
      tags:
        - Party
      parameters:
        - name: party_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the party
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PartyIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Add party identification
      description: Add a new identification to a party
      operationId: addPartyIdentification
      tags:
        - Party
      parameters:
        - name: party_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the party
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartyIdentificationCreate'
      responses:
        '201':
          description: Identification added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartyIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /parties/{party_id}/locations:
    get:
      summary: Get party locations
      description: Retrieve all locations for a specific party
      operationId: getPartyLocations
      tags:
        - Party
      parameters:
        - name: party_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the party
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PartyLocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Add party location
      description: Add a new location to a party
      operationId: addPartyLocation
      tags:
        - Party
      parameters:
        - name: party_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the party
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartyLocationCreate'
      responses:
        '201':
          description: Location added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartyLocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /parties/{party_id}/contact-points:
    get:
      summary: Get party contact points
      description: Retrieve all contact points for a specific party
      operationId: getPartyContactPoints
      tags:
        - Party
      parameters:
        - name: party_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the party
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ContactPoint'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Add party contact point
      description: Add a new contact point to a party
      operationId: addPartyContactPoint
      tags:
        - Party
      parameters:
        - name: party_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the party
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactPointCreate'
      responses:
        '201':
          description: Contact point added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactPoint'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError' 