UnmergeResponse:
  type: object
  properties:
    unmerge_id:
      type: string
      description: Unique identifier for this unmerge operation
    original_merge_id:
      type: string
      description: ID of the original merge operation
    survivor_party_id:
      type: string
      description: ID of the previously surviving party
    unmerged_party_ids:
      type: array
      items:
        type: string
      description: IDs of unmerged parties
    unmerge_date:
      type: string
      format: date-time
      description: Date and time when the unmerge was performed
    unmerge_reason:
      type: string
      description: Reason for the unmerge
    unmerge_by:
      type: string
      description: User who performed the unmerge

MatchRuleListItem:
  type: object
  properties:
    match_rule_id:
      type: string
      description: Unique identifier for this match rule
    rule_name:
      type: string
      description: Name of the match rule
    rule_type:
      type: string
      enum: [Exact, Fuzzy, Deterministic, Probabilistic, Hybrid]
      description: Type of match rule
    party_type:
      type: string
      enum: [Person, Organization, Both]
      description: Type of party this rule applies to
    priority:
      type: integer
      description: Priority of this rule in the matching hierarchy
    is_active:
      type: boolean
      description: Flag indicating if this rule is active

MatchRuleCreate:
  type: object
  required:
    - rule_name
    - rule_type
    - rule_definition
    - threshold
    - priority
  properties:
    rule_name:
      type: string
      description: Name of the match rule
    rule_description:
      type: string
      description: Description of the match rule
      nullable: true
    rule_type:
      type: string
      enum: [Exact, Fuzzy, Deterministic, Probabilistic, Hybrid]
      description: Type of match rule
    rule_definition:
      type: object
      description: Definition of the match rule in JSON format
      additionalProperties: true
    threshold:
      type: number
      format: double
      minimum: 0
      maximum: 100
      description: Threshold for considering a match (0-100)
    priority:
      type: integer
      minimum: 1
      description: Priority of this rule in the matching hierarchy
    party_type:
      type: string
      enum: [Person, Organization, Both]
      default: Both
      description: Type of party this rule applies to
    is_active:
      type: boolean
      default: true
      description: Flag indicating if this rule is active

MatchRuleResponse:
  type: object
  properties:
    match_rule_id:
      type: string
      description: Unique identifier for this match rule
    rule_name:
      type: string
      description: Name of the match rule
    rule_description:
      type: string
      description: Description of the match rule
      nullable: true
    rule_type:
      type: string
      enum: [Exact, Fuzzy, Deterministic, Probabilistic, Hybrid]
      description: Type of match rule
    rule_definition:
      type: object
      description: Definition of the match rule in JSON format
      additionalProperties: true
    threshold:
      type: number
      format: double
      description: Threshold for considering a match (0-100)
    priority:
      type: integer
      description: Priority of this rule in the matching hierarchy
    party_type:
      type: string
      enum: [Person, Organization, Both]
      description: Type of party this rule applies to
    is_active:
      type: boolean
      description: Flag indicating if this rule is active
    timestamps:
      $ref: '#/components/schemas/Timestamp'

responses:
  BadRequest:
    description: Bad request - invalid input
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'

  Unauthorized:
    description: Unauthorized - authentication required
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'

  Forbidden:
    description: Forbidden - insufficient permissions
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'

  NotFound:
    description: Resource not found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'

  Conflict:
    description: Conflict with current state
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'

  InternalServerError:
    description: Internal server error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'

  Error:
    type: object
    properties:
      code:
        type: string
        description: Error code
      message:
        type: string
        description: Error message
      details:
        type: array
        items:
          type: object
          additionalProperties: true
        description: Additional error details
        nullable: true 